const productCatalog = {
  "cosmicorbit-lite": {
    key: "cosmicorbit-lite",
    name: "CosmicOrbit Lite",
    family: "CosmicOrbit",
    version: "Lite",
    price: 39,
    priceLabel: "$39",
    originalPrice: 59,
    originalPriceLabel: "$59",
    image: "images/cosmicorbit-lite.png",
    preview: "preview/CosmicOrbit-Lite/index.html",
    downloadFile: "downloads/CosmicOrbit-Lite.zip",
    successUrl: "thank-you-lite.html?product=cosmicorbit-lite",
    tagline: "Launch Promo",
    typeLabel: "Single-page template",
    description: "A bold futuristic single-page website template for digital brands, creators, startups, and service businesses that want a polished launch without starting from scratch.",
    features: [
      "Single-page website",
      "Responsive layout",
      "Editable HTML, CSS, and JavaScript",
      "Documentation included",
      "Commercial use license",
      "Instant digital download"
    ]
  },
  "cosmicorbit-pro": {
    key: "cosmicorbit-pro",
    name: "CosmicOrbit Pro",
    family: "CosmicOrbit",
    version: "Pro",
    price: 69,
    priceLabel: "$69",
    originalPrice: 99,
    originalPriceLabel: "$99",
    image: "images/cosmicorbit-pro.png",
    preview: "preview/CosmicOrbit-Pro/index.html",
    downloadFile: "downloads/CosmicOrbit-Pro.zip",
    successUrl: "thank-you-pro.html?product=cosmicorbit-pro",
    tagline: "Launch Promo",
    typeLabel: "Multi-page template",
    description: "A premium futuristic multi-page website template with stronger layouts, expanded sections, and a polished experience for modern online brands.",
    features: [
      "Multi-page website",
      "More sections and pages",
      "Stronger layouts for polished launches",
      "Responsive layout",
      "Editable HTML, CSS, and JavaScript",
      "Documentation included",
      "Commercial use license",
      "Instant digital download"
    ]
  },
  "abyssalblue-lite": {
    key: "abyssalblue-lite",
    name: "Abyssal Blue Lite",
    family: "Abyssal Blue",
    version: "Lite",
    price: 39,
    priceLabel: "$39",
    originalPrice: 59,
    originalPriceLabel: "$59",
    image: "images/abyssalblue-lite.png",
    preview: "preview/AbyssalBlue-Lite/index.html",
    downloadFile: "downloads/AbyssalBlue-Lite.zip",
    successUrl: "thank-you-lite.html?product=abyssalblue-lite",
    tagline: "Launch Promo",
    typeLabel: "Single-page template",
    description: "A clean ocean-inspired single-page template suited for travel brands, tours, attractions, wellness businesses, and modern service sites.",
    features: [
      "Single-page website",
      "Responsive layout",
      "Editable HTML, CSS, and JavaScript",
      "Documentation included",
      "Commercial use license",
      "Instant digital download"
    ]
  },
  "abyssalblue-pro": {
    key: "abyssalblue-pro",
    name: "Abyssal Blue Pro",
    family: "Abyssal Blue",
    version: "Pro",
    price: 69,
    priceLabel: "$69",
    originalPrice: 99,
    originalPriceLabel: "$99",
    image: "images/abyssalblue-pro.png",
    preview: "preview/AbyssalBlue-Pro/index.html",
    downloadFile: "downloads/AbyssalBlue-Pro.zip",
    successUrl: "thank-you-pro.html?product=abyssalblue-pro",
    tagline: "Launch Promo",
    typeLabel: "Multi-page template",
    description: "A premium underwater-inspired multi-page template with richer storytelling, additional pages, and stronger layouts for a more complete launch.",
    features: [
      "Multi-page website",
      "More sections and pages",
      "Stronger layouts for polished launches",
      "Responsive layout",
      "Editable HTML, CSS, and JavaScript",
      "Documentation included",
      "Commercial use license",
      "Instant digital download"
    ]
  },
  "velvetui-lite": {
    key: "velvetui-lite",
    name: "VelvetUI Lite",
    family: "VelvetUI",
    version: "Lite",
    price: 39,
    priceLabel: "$39",
    originalPrice: 59,
    originalPriceLabel: "$59",
    image: "images/velvetui-lite.png",
    preview: "preview/VelvetUI-Lite/index.html",
    downloadFile: "downloads/VelvetUI-Lite.zip",
    successUrl: "thank-you-lite.html?product=velvetui-lite",
    tagline: "Launch Promo",
    typeLabel: "Single-page template",
    description: "A soft luxury single-page template for personal brands, coaches, beauty businesses, digital offers, and modern promotional websites.",
    features: [
      "Single-page website",
      "Responsive layout",
      "Editable HTML, CSS, and JavaScript",
      "Documentation included",
      "Commercial use license",
      "Instant digital download"
    ]
  },
  "velvetui-pro": {
    key: "velvetui-pro",
    name: "VelvetUI Pro",
    family: "VelvetUI",
    version: "Pro",
    price: 69,
    priceLabel: "$69",
    originalPrice: 99,
    originalPriceLabel: "$99",
    image: "images/velvetui-pro.png",
    preview: "preview/VelvetUI-Pro/index.html",
    downloadFile: "downloads/VelvetUI-Pro.zip",
    successUrl: "thank-you-pro.html?product=velvetui-pro",
    tagline: "Launch Promo",
    typeLabel: "Multi-page template",
    description: "A luxury multi-page glassmorphism template with stronger page flow, more content areas, and a polished premium presentation.",
    features: [
      "Multi-page website",
      "More sections and pages",
      "Stronger layouts for polished launches",
      "Responsive layout",
      "Editable HTML, CSS, and JavaScript",
      "Documentation included",
      "Commercial use license",
      "Instant digital download"
    ]
  },
  "worldviewglobal-lite": {
    key: "worldviewglobal-lite",
    name: "WorldView Global Lite",
    family: "WorldView Global",
    version: "Lite",
    price: 39,
    priceLabel: "$39",
    originalPrice: 59,
    originalPriceLabel: "$59",
    image: "images/worldviewglobal-pro.png",
    preview: "preview/WorldViewGlobal-Lite/index.html",
    downloadFile: "downloads/WorldViewGlobal-Lite.zip",
    successUrl: "thank-you-lite.html?product=worldviewglobal-lite",
    tagline: "Launch Promo",
    typeLabel: "Single-page template",
    description: "A professional single-page business template for agencies, consultants, startups, and service-based brands that need a clean online presence.",
    features: [
      "Single-page website",
      "Responsive layout",
      "Editable HTML, CSS, and JavaScript",
      "Documentation included",
      "Commercial use license",
      "Instant digital download"
    ]
  },
  "worldviewglobal-pro": {
    key: "worldviewglobal-pro",
    name: "WorldView Global Pro",
    family: "WorldView Global",
    version: "Pro",
    price: 69,
    priceLabel: "$69",
    originalPrice: 99,
    originalPriceLabel: "$99",
    image: "images/worldviewglobal-pro.png",
    preview: "preview/WorldViewGlobal-Pro/index.html",
    downloadFile: "downloads/WorldViewGlobal-Pro.zip",
    successUrl: "thank-you-pro.html?product=worldviewglobal-pro",
    tagline: "Launch Promo",
    typeLabel: "Multi-page template",
    description: "A polished multi-page business template with stronger layouts, additional business-ready sections, and a more complete website structure.",
    features: [
      "Multi-page website",
      "More sections and pages",
      "Stronger layouts for polished launches",
      "Responsive layout",
      "Editable HTML, CSS, and JavaScript",
      "Documentation included",
      "Commercial use license",
      "Instant digital download"
    ]
  },
  "rainblossom-lite": {
    key: "rainblossom-lite",
    name: "Rain Blossom Lite",
    family: "Rain Blossom",
    version: "Lite",
    price: 39,
    priceLabel: "$39",
    originalPrice: 59,
    originalPriceLabel: "$59",
    image: "images/rainblossom-lite.svg",
    preview: "preview/RainBlossom-Lite/index.html",
    downloadFile: "downloads/RainBlossom-Lite.zip",
    successUrl: "thank-you-lite.html?product=rainblossom-lite",
    tagline: "New Arrival",
    typeLabel: "Single-page template",
    description: "A romantic, editorial-style single-page template for florists, beauty brands, event creatives, and boutique service businesses that want a polished feminine launch.",
    features: [
      "Single-page website",
      "Editorial-inspired layout",
      "Responsive desktop, tablet, and mobile design",
      "Editable HTML and CSS",
      "Documentation included",
      "Instant digital download"
    ]
  },
  "rainblossom-pro": {
    key: "rainblossom-pro",
    name: "Rain Blossom Pro",
    family: "Rain Blossom",
    version: "Pro",
    price: 69,
    priceLabel: "$69",
    originalPrice: 99,
    originalPriceLabel: "$99",
    image: "images/rainblossom-pro.svg",
    preview: "preview/RainBlossom-Pro/index.html",
    downloadFile: "downloads/RainBlossom-Pro.zip",
    successUrl: "thank-you-pro.html?product=rainblossom-pro",
    tagline: "New Arrival",
    typeLabel: "Multi-page template",
    description: "A romantic multi-page template with richer storytelling, polished service sections, and a premium boutique presentation for beauty, fashion, and event-led brands.",
    features: [
      "Multi-page website",
      "Home, about, and contact pages",
      "Responsive desktop, tablet, and mobile design",
      "Editable HTML and CSS",
      "Documentation included",
      "Instant digital download"
    ]
  }
};

if (typeof window !== "undefined") {
  window.productCatalog = productCatalog;
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = productCatalog;
}
