const productCatalog = {
  "techpulse-it-wordpress": {
    key: "techpulse-it-wordpress",
    name: "TechPulse IT Services WordPress Theme",
    family: "TechPulse IT",
    version: "WordPress",
    price: 29.99,
    priceLabel: "$29.99",
    originalPrice: 59.98,
    originalPriceLabel: "$59.98",
    image: "images/TechPulse IT/home.png",
    galleryImages: [
      { src: "images/TechPulse IT/home.png", label: "Homepage - 1/3", altLabel: "Homepage" },
      { src: "images/TechPulse IT/services.png", label: "Services - 2/3", altLabel: "Services" },
      { src: "images/TechPulse IT/pricing.png", label: "Pricing - 3/3", altLabel: "Pricing" }
    ],
    preview: "preview/Word%20Press/TechPuseIT-demo.mp4",
    downloadFile: "downloads/techpulse-it.zip",
    successUrl: "thank-you.html?session_id={CHECKOUT_SESSION_ID}",
    productPageUrl: "techpulse-it-services-wordpress-theme.html",
    tagline: "Launch Discount",
    typeLabel: "WordPress Theme",
    category: "IT Services / Tech Support",
    tags: ["WordPress","IT Services","Tech Support","Local Business","Pro","wordpress","tech","it-services","tech-support","local-business"],
    description: "A professional WordPress theme for IT companies, managed service providers, cybersecurity firms, and tech support businesses that need a credible, lead-focused website.",
    features: [
      "WordPress theme",
      "Business-ready layout",
      "Responsive design",
      "Editable theme files",
      "Documentation included",
      "Instant digital download"
    ]
  },
  freshnest: {
    key: "freshnest",
    name: "FreshNest Cleaning Website Template",
    family: "FreshNest",
    version: "Lite",
    price: 9.99,
    priceLabel: "$9.99",
    originalPrice: 19.98,
    originalPriceLabel: "$19.98",
    image: "images/FreshNest/freshnest-index.png",
    galleryImages: [
      { src: "images/FreshNest/freshnest-index.png", label: "Homepage - 1/3", altLabel: "Homepage" },
      { src: "images/FreshNest/freshnest-services.png", label: "Services - 2/3", altLabel: "Services" },
      { src: "images/FreshNest/freshnest-pricing.png", label: "Pricing - 3/3", altLabel: "Pricing" }
    ],
    preview: "preview/FreshNest%20Cleaning/index.html",
    downloadFile: "downloads/FreshNest Cleaning.zip",
    successUrl: "thank-you.html?session_id={CHECKOUT_SESSION_ID}",
    productPageUrl: "freshnest-cleaning-website-template.html",
    tagline: "50% Off Launch Discount",
    typeLabel: "Landing Page",
    category: "Cleaning companies and home service businesses",
    tags: ["Cleaning Business","Home Services","Local Business","HTML Website","landing-page","html-website","business","cleaning-business","home-services","local-business"],
    description: "A responsive cleaning business landing page template with service highlights, trust-building sections, pricing content, and clear calls to action for local leads.",
    features: [
      "Single-page landing page",
      "Responsive layout",
      "Editable HTML, CSS, and JavaScript",
      "Documentation included",
      "Commercial use license",
      "Instant digital download"
    ]
  },
  "rainblossom-lite": {
    key: "rainblossom-lite",
    name: "Rain Blossom Lite Wedding Landing Page Template",
    family: "Rain Blossom",
    version: "Lite",
    price: 9.99,
    priceLabel: "$9.99",
    originalPrice: 19.98,
    originalPriceLabel: "$19.98",
    image: "images/Rain Blossom Lite/rainblossom-lite.png",
    galleryImages: [
      { src: "images/Rain Blossom Lite/rainblossom-lite.png", label: "Homepage - 1/3", altLabel: "Homepage" },
      { src: "images/Rain Blossom Lite/rainblossom-lite-gallery.png", label: "Gallery - 2/3", altLabel: "Gallery" },
      { src: "images/Rain Blossom Lite/rainblossom-lite-contact.png", label: "Contact - 3/3", altLabel: "Contact" }
    ],
    preview: "preview/RainBlossom-Lite/index.html",
    downloadFile: "downloads/RainBlossom-Lite.zip",
    successUrl: "thank-you.html?session_id={CHECKOUT_SESSION_ID}",
    productPageUrl: "rain-blossom-lite-wedding-landing-page.html",
    tagline: "50% Off Launch Discount",
    typeLabel: "Landing Page",
    category: "Wedding planners and event coordinators",
    tags: ["Wedding","Event Planning","Landing Page","HTML Website","landing-page","html-website","creative","wedding","event-planning","local-business"],
    description: "A romantic wedding landing page template for planners and venues, with polished package, gallery, testimonial, and inquiry sections in a responsive HTML design.",
    features: [
      "Single-page wedding website",
      "Responsive layout",
      "Editable HTML, CSS, and JavaScript",
      "Documentation included",
      "Commercial use license",
      "Instant digital download"
    ]
  },
  "rainblossom-pro": {
    key: "rainblossom-pro",
    name: "Rain Blossom Pro Wedding Website Template",
    family: "Rain Blossom",
    version: "Pro",
    price: 19.99,
    priceLabel: "$19.99",
    originalPrice: 39.98,
    originalPriceLabel: "$39.98",
    image: "images/Rain Blossom Pro/rainblossom-pro.png",
    galleryImages: [
      { src: "images/Rain Blossom Pro/rainblossom-pro.png", label: "Homepage - 1/3", altLabel: "Homepage" },
      { src: "images/Rain Blossom Pro/rainblossom-about.png", label: "About - 2/3", altLabel: "About" },
      { src: "images/Rain Blossom Pro/rainblossom-contact-pro.png", label: "Contact - 3/3", altLabel: "Contact" }
    ],
    preview: "preview/RainBlossom-Pro/index.html",
    downloadFile: "downloads/RainBlossom-Pro.zip",
    successUrl: "thank-you.html?session_id={CHECKOUT_SESSION_ID}",
    productPageUrl: "rain-blossom-pro-wedding-website-template.html",
    tagline: "50% Off Launch Discount",
    typeLabel: "HTML Website",
    category: "Wedding planners and event coordinators",
    tags: ["Wedding","Event Planning","HTML Website","Local Business","full-website","html-website","creative","wedding","event-planning","local-business"],
    description: "A romantic multi-page wedding website template for planners and venues, featuring galleries, packages, testimonials, FAQs, and a complete inquiry flow.",
    features: [
      "Multi-page wedding website",
      "More sections and pages",
      "Responsive layout",
      "Editable HTML, CSS, and JavaScript",
      "Documentation included",
      "Instant digital download"
    ]
  },
  "apexmobile-detailing": {
    key: "apexmobile-detailing",
    name: "Apex Mobile Detailing Website Template",
    family: "Apex Mobile Detailing",
    version: "Full Website",
    price: 19.99,
    priceLabel: "$19.99",
    originalPrice: 39.98,
    originalPriceLabel: "$39.98",
    image: "images/Apex Mobile Detailing/apex-home.png",
    galleryImages: [
      { src: "images/Apex Mobile Detailing/apex-home.png", label: "Homepage - 1/3", altLabel: "Homepage" },
      { src: "images/Apex Mobile Detailing/apex-services.png", label: "Services - 2/3", altLabel: "Services" },
      { src: "images/Apex Mobile Detailing/apex-gallery.png", label: "Gallery - 3/3", altLabel: "Gallery" }
    ],
    preview: "preview/ApexMobile-Detailing/index.html",
    downloadFile: "downloads/ApexMobile-Detailing.zip",
    successUrl: "thank-you.html?session_id={CHECKOUT_SESSION_ID}",
    productPageUrl: "apex-mobile-detailing-website-template.html",
    tagline: "50% Off Launch Discount",
    typeLabel: "Multi-page template",
    category: "Mobile detailing, auto care, and local service businesses",
    tags: ["Auto Detailing","Local Business","HTML Website","full-website","html-website","business","auto-detailing","home-services","local-business"],
    description: "A responsive multi-page auto detailing website template with services, pricing, project gallery, and booking-focused contact pages for mobile detailers.",
    features: ["Multi-page website", "Service and pricing pages", "Gallery-ready layout", "Responsive layout", "Editable HTML, CSS, and JavaScript", "Documentation included", "Commercial use license", "Instant digital download"]
  },
  beachwave: {
    key: "beachwave",
    name: "BeachWave Resort Website Template",
    family: "BeachWave",
    version: "Full Website",
    price: 19.99,
    priceLabel: "$19.99",
    originalPrice: 39.98,
    originalPriceLabel: "$39.98",
    image: "images/Beach Wave/beachwave-mobile.png",
    galleryImages: [
      { src: "images/Beach Wave/beachwave-mobile.png", label: "Homepage - 1/3", altLabel: "Homepage" },
      { src: "images/Beach Wave/beachwave-gallery.png", label: "Gallery - 2/3", altLabel: "Gallery" },
      { src: "images/Beach Wave/beachwave-contact.png", label: "Contact - 3/3", altLabel: "Contact" }
    ],
    preview: "preview/BeachWave/index.html",
    downloadFile: "downloads/BeachWave.zip",
    successUrl: "thank-you.html?session_id={CHECKOUT_SESSION_ID}",
    productPageUrl: "beachwave-resort-website-template.html",
    tagline: "50% Off Launch Discount",
    typeLabel: "Multi-page template",
    category: "Resorts, vacation rentals, beach clubs, travel brands, and hospitality businesses",
    tags: ["Travel","Hospitality","HTML Website","full-website","html-website","travel","creative","hospitality","tourism","local-business"],
    description: "A premium animated resort website template for hotels, vacation rentals, beach clubs, and travel brands, with pages for stays, amenities, galleries, pricing, FAQs, and inquiries.",
    features: ["Multi-page website", "Animated resort-style experience", "Gallery and FAQ pages", "Responsive layout", "Editable HTML, CSS, and JavaScript", "Documentation included", "Commercial use license", "Instant digital download"]
  },
  "cosmicorbit-lite": {
    key: "cosmicorbit-lite",
    name: "Cosmic Orbit Lite Creative Website Template",
    family: "CosmicOrbit",
    version: "Lite",
    price: 9.99,
    priceLabel: "$9.99",
    originalPrice: 19.98,
    originalPriceLabel: "$19.98",
    image: "images/Cosmic Orbit Lite/cosmicorbit-lite.png",
    galleryImages: [
      { src: "images/Cosmic Orbit Lite/cosmicorbit-lite.png", label: "Homepage - 1/3", altLabel: "Homepage" },
      { src: "images/Cosmic Orbit Lite/cosmicorbit-lite-about.png", label: "About Section - 2/3", altLabel: "About Section" },
      { src: "images/Cosmic Orbit Lite/cosmicorbit-lite-footer.png", label: "Footer - 3/3", altLabel: "Footer" }
    ],
    preview: "preview/CosmicOrbit-Lite/index.html",
    downloadFile: "downloads/CosmicOrbit-Lite.zip",
    successUrl: "thank-you.html?session_id={CHECKOUT_SESSION_ID}",
    productPageUrl: "cosmic-orbit-lite-creative-website-template.html",
    tagline: "50% Off Launch Discount",
    typeLabel: "Single-page template",
    category: "Futuristic brands, event experiences, digital launches, and creative service businesses",
    tags: ["Creative","Tech","Travel","full-website","html-website","travel","tech","creative","business"],
    description: "A bold futuristic website template for creators, startups, digital brands, and event launches that want a responsive, high-impact online presence.",
    features: ["Single-page website", "Responsive layout", "Editable HTML, CSS, and JavaScript", "Documentation included", "Commercial use license", "Instant digital download"]
  },
  "cosmicorbit-pro": {
    key: "cosmicorbit-pro",
    name: "Cosmic Orbit Pro Creative Business Website Template",
    family: "CosmicOrbit",
    version: "Pro",
    price: 19.99,
    priceLabel: "$19.99",
    originalPrice: 39.98,
    originalPriceLabel: "$39.98",
    image: "images/Cosmic Orbit Pro/cosmicorbit-pro-home.png",
    galleryImages: [
      { src: "images/Cosmic Orbit Pro/cosmicorbit-pro-home.png", label: "Homepage - 1/3", altLabel: "Homepage" },
      { src: "images/Cosmic Orbit Pro/cosmicorbit-pro-contact.png", label: "Contact Form - 2/3", altLabel: "Contact Form" },
      { src: "images/Cosmic Orbit Pro/cosmicorbit-pro-thankyou.png", label: "Thank You Page - 3/3", altLabel: "Thank You Page" }
    ],
    preview: "preview/CosmicOrbit-Pro/index.html",
    downloadFile: "downloads/CosmicOrbit-Pro.zip",
    successUrl: "thank-you.html?session_id={CHECKOUT_SESSION_ID}",
    productPageUrl: "cosmic-orbit-pro-creative-business-template.html",
    tagline: "50% Off Launch Discount",
    typeLabel: "Multi-page template",
    category: "Futuristic brands, event experiences, digital launches, and creative service businesses",
    tags: ["Creative","Tech","Travel","full-website","html-website","travel","tech","creative","business"],
    description: "A premium futuristic multi-page website template for creative businesses, launches, events, and digital services, with polished layouts and conversion-focused sections.",
    features: ["Multi-page website", "More sections and pages", "Stronger layouts for polished launches", "Responsive layout", "Editable HTML, CSS, and JavaScript", "Documentation included", "Commercial use license", "Instant digital download"]
  },
  "abyssalblue-lite": {
    key: "abyssalblue-lite",
    name: "Abyssal Blue Lite Tourism Website Template",
    family: "Abyssal Blue",
    version: "Lite",
    price: 9.99,
    priceLabel: "$9.99",
    originalPrice: 19.98,
    originalPriceLabel: "$19.98",
    image: "images/Abyssal Blue Lite/abyssalblue-lite.png",
    galleryImages: [
      { src: "images/Abyssal Blue Lite/abyssalblue-lite.png", label: "Homepage - 1/3", altLabel: "Homepage" },
      { src: "images/Abyssal Blue Lite/abyssalblue-lite-contact.png", label: "Contact Form - 2/3", altLabel: "Contact Form" },
      { src: "images/Abyssal Blue Lite/abyssalblue-lite-footer.png", label: "Footer - 3/3", altLabel: "Footer" }
    ],
    preview: "preview/AbyssalBlue-Lite/index.html",
    downloadFile: "downloads/AbyssalBlue-Lite.zip",
    successUrl: "thank-you.html?session_id={CHECKOUT_SESSION_ID}",
    productPageUrl: "abyssal-blue-lite-tourism-website-template.html",
    tagline: "50% Off Launch Discount",
    typeLabel: "Single-page template",
    category: "Aquariums, attractions, tourism brands, and experience businesses",
    tags: ["Travel","Tourism","Aquarium","full-website","html-website","travel","creative","tourism","aquarium","local-business"],
    description: "An immersive tourism website template for aquariums, attractions, tours, and experience brands, with responsive visitor-focused sections and ocean-inspired visuals.",
    features: ["Single-page website", "Responsive layout", "Editable HTML, CSS, and JavaScript", "Documentation included", "Commercial use license", "Instant digital download"]
  },
  "abyssalblue-pro": {
    key: "abyssalblue-pro",
    name: "Abyssal Blue Pro Aquarium Website Template",
    family: "Abyssal Blue",
    version: "Pro",
    price: 19.99,
    priceLabel: "$19.99",
    originalPrice: 39.98,
    originalPriceLabel: "$39.98",
    image: "images/Abyssal Blue Pro/abyssalblue-pro.png",
    galleryImages: [
      { src: "images/Abyssal Blue Pro/abyssalblue-pro.png", label: "Homepage - 1/3", altLabel: "Homepage" },
      { src: "images/Abyssal Blue Pro/abyssalblue-pro-booking.png", label: "Booking Page - 2/3", altLabel: "Booking Page" },
      { src: "images/Abyssal Blue Pro/abyssalblue-pro-gallery.png", label: "Gallery Page - 3/3", altLabel: "Gallery Page" }
    ],
    preview: "preview/AbyssalBlue-Pro/index.html",
    downloadFile: "downloads/AbyssalBlue-Pro.zip",
    successUrl: "thank-you.html?session_id={CHECKOUT_SESSION_ID}",
    productPageUrl: "abyssal-blue-pro-aquarium-website-template.html",
    tagline: "50% Off Launch Discount",
    typeLabel: "Multi-page template",
    category: "Aquariums, attractions, tourism brands, and experience businesses",
    tags: ["Travel","Tourism","Aquarium","full-website","html-website","travel","creative","tourism","aquarium","local-business"],
    description: "A premium multi-page aquarium and tourism website template with booking, gallery, wildlife, visitor information, and contact pages for attraction-based businesses.",
    features: ["Multi-page website", "More sections and pages", "Stronger layouts for polished launches", "Responsive layout", "Editable HTML, CSS, and JavaScript", "Documentation included", "Commercial use license", "Instant digital download"]
  },
  "velvetui-lite": {
    key: "velvetui-lite",
    name: "Velvet UI Lite Interior Design Website Template",
    family: "VelvetUI",
    version: "Lite",
    price: 9.99,
    priceLabel: "$9.99",
    originalPrice: 19.98,
    originalPriceLabel: "$19.98",
    image: "images/VelvetUI Lite/velvetui-lite-home.png",
    galleryImages: [
      { src: "images/VelvetUI Lite/velvetui-lite-home.png", label: "Homepage - 1/3", altLabel: "Homepage" },
      { src: "images/VelvetUI Lite/velvetui-lite-contact.png", label: "Contact Form - 2/3", altLabel: "Contact Form" },
      { src: "images/VelvetUI Lite/velvetui-lite-footer.png", label: "Footer - 3/3", altLabel: "Footer" }
    ],
    preview: "preview/VelvetUI-Lite/index.html",
    downloadFile: "downloads/VelvetUI-Lite.zip",
    successUrl: "thank-you.html?session_id={CHECKOUT_SESSION_ID}",
    productPageUrl: "velvet-ui-lite-interior-design-template.html",
    tagline: "50% Off Launch Discount",
    typeLabel: "Single-page template",
    category: "Home design studios, interior designers, portfolios, and boutique creative brands",
    tags: ["Home Design","Portfolio","Creative","full-website","html-website","portfolio","creative","business","home-design"],
    description: "A refined interior design website template for home stylists, boutique studios, and portfolio-led creative businesses that need an elegant responsive showcase.",
    features: ["Single-page website", "Responsive layout", "Editable HTML, CSS, and JavaScript", "Documentation included", "Commercial use license", "Instant digital download"]
  },
  "velvetui-pro": {
    key: "velvetui-pro",
    name: "Velvet UI Pro Interior Design Website Template",
    family: "VelvetUI",
    version: "Pro",
    price: 19.99,
    priceLabel: "$19.99",
    originalPrice: 39.98,
    originalPriceLabel: "$39.98",
    image: "images/VelvetUI Pro/velvetui-pro.png",
    galleryImages: [
      { src: "images/VelvetUI Pro/velvetui-pro.png", label: "Homepage - 1/3", altLabel: "Homepage" },
      { src: "images/VelvetUI Pro/velvetui-pro-contact.png", label: "Contact Form - 2/3", altLabel: "Contact Form" },
      { src: "images/VelvetUI Pro/velvetui-pro-faq.png", label: "FAQ Page - 3/3", altLabel: "FAQ Page" }
    ],
    preview: "preview/VelvetUI-Pro/index.html",
    downloadFile: "downloads/VelvetUI-Pro.zip",
    successUrl: "thank-you.html?session_id={CHECKOUT_SESSION_ID}",
    productPageUrl: "velvet-ui-pro-interior-design-template.html",
    tagline: "50% Off Launch Discount",
    typeLabel: "Multi-page template",
    category: "Home design studios, interior designers, portfolios, and boutique creative brands",
    tags: ["Home Design","Portfolio","Creative","full-website","html-website","portfolio","creative","business","home-design"],
    description: "A premium multi-page interior design website template with portfolio, services, project showcase, FAQ, and contact pages for studios and luxury creative brands.",
    features: ["Multi-page website", "More sections and pages", "Stronger layouts for polished launches", "Responsive layout", "Editable HTML, CSS, and JavaScript", "Documentation included", "Commercial use license", "Instant digital download"]
  },
  "worldviewglobal-lite": {
    key: "worldviewglobal-lite",
    name: "WorldView Global Lite Business Website Template",
    family: "WorldView Global",
    version: "Lite",
    price: 9.99,
    priceLabel: "$9.99",
    originalPrice: 19.98,
    originalPriceLabel: "$19.98",
    image: "images/WorldView Lite/worldview-lite.png",
    galleryImages: [
      { src: "images/WorldView Lite/worldview-lite.png", label: "Homepage - 1/3", altLabel: "Homepage" },
      { src: "images/WorldView Lite/worldview-lite-contact.png", label: "Contact Form - 2/3", altLabel: "Contact Form" },
      { src: "images/WorldView Lite/worldview-lite-footer.png", label: "Footer - 3/3", altLabel: "Footer" }
    ],
    preview: "preview/WorldViewGlobal-Lite/index.html",
    downloadFile: "downloads/WorldViewGlobal-Lite.zip",
    successUrl: "thank-you.html?session_id={CHECKOUT_SESSION_ID}",
    productPageUrl: "worldview-global-lite-business-template.html",
    tagline: "50% Off Launch Discount",
    typeLabel: "Single-page template",
    category: "Consultants, agencies, startups, and professional service businesses",
    tags: ["Business","Consulting","HTML Website","full-website","html-website","business","consulting"],
    description: "A professional business website template for consultants, agencies, startups, and service providers that need a responsive, credible online presence.",
    features: ["Single-page website", "Responsive layout", "Editable HTML, CSS, and JavaScript", "Documentation included", "Commercial use license", "Instant digital download"]
  },
  "worldviewglobal-pro": {
    key: "worldviewglobal-pro",
    name: "WorldView Global Pro Business Website Template",
    family: "WorldView Global",
    version: "Pro",
    price: 19.99,
    priceLabel: "$19.99",
    originalPrice: 39.98,
    originalPriceLabel: "$39.98",
    image: "images/WorldView Pro/worldview-pro.png",
    galleryImages: [
      { src: "images/WorldView Pro/worldview-pro.png", label: "Homepage - 1/3", altLabel: "Homepage" },
      { src: "images/WorldView Pro/worldview-pro-contact.png", label: "Contact Form - 2/3", altLabel: "Contact Form" },
      { src: "images/WorldView Pro/worldview-pro-footer.png", label: "Footer - 3/3", altLabel: "Footer" }
    ],
    preview: "preview/WorldViewGlobal-Pro/index.html",
    downloadFile: "downloads/WorldViewGlobal-Pro.zip",
    successUrl: "thank-you.html?session_id={CHECKOUT_SESSION_ID}",
    productPageUrl: "worldview-global-pro-business-template.html",
    tagline: "50% Off Launch Discount",
    typeLabel: "Multi-page template",
    category: "Consultants, agencies, startups, and professional service businesses",
    tags: ["Business","Consulting","HTML Website","full-website","html-website","business","consulting"],
    description: "A premium multi-page business website template with solutions, use cases, showcase, pricing, FAQ, and contact pages for agencies and professional service companies.",
    features: ["Multi-page website", "More sections and pages", "Stronger layouts for polished launches", "Responsive layout", "Editable HTML, CSS, and JavaScript", "Documentation included", "Commercial use license", "Instant digital download"]
  }
};

if (typeof window !== "undefined") {
  window.productCatalog = productCatalog;
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = productCatalog;
}
